version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: ws-chat-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # この辺は必要なら適宜
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    restart: always